import { scoreLead } from "@/lib/scoring";
import type { Lead } from "@/lib/types";

const now = new Date();
const day = 24 * 60 * 60 * 1000;

const seed: Omit<Lead, "lead_score" | "created_at" | "updated_at">[] = [
  {
    id: "lead_ca_1",
    company_name: "Northline Dental Studio",
    region: "Canada",
    country: "Canada",
    city: "Toronto",
    category: "Dental clinic",
    business_type: "Local healthcare",
    website: "https://northline.example",
    google_maps_url: "https://maps.google.com/?q=Northline+Dental+Studio",
    phone: "+14165550188",
    email: "hello@northline.example",
    whatsapp_available: true,
    whatsapp_status: "available",
    owner_name: null,
    ceo_name: null,
    manager_name: "Maya Singh",
    linkedin_url: null,
    source_platform: "google_places",
    outreach_status: "Contacted",
    outreach_approved: false,
    outreach_approved_at: null,
    email_sent: true,
    whatsapp_sent: true,
    replied: false,
    last_contacted_at: new Date(now.getTime() - day).toISOString(),
    next_follow_up_at: new Date(now.getTime() + day * 2).toISOString(),
    notes: "Good fit for GMB optimization and review growth.",
    rating: 3.6,
    review_count: 8,
    missing_seo_metadata: true,
    contact_forms: [],
    do_not_contact: false,
    consent_status: "legitimate_interest",
    unsubscribed: false
  },
  {
    id: "lead_us_1",
    company_name: "Canyon Peak Roofing",
    region: "USA",
    country: "United States",
    city: "Phoenix",
    category: "Roofing contractor",
    business_type: "Home services",
    website: null,
    google_maps_url: "https://maps.google.com/?q=Canyon+Peak+Roofing",
    phone: "+16025550144",
    email: "owner@canyonpeak.example",
    whatsapp_available: false,
    whatsapp_status: "unknown",
    owner_name: "Daniel Reyes",
    ceo_name: null,
    manager_name: null,
    linkedin_url: null,
    source_platform: "google_places",
    outreach_status: "New",
    outreach_approved: false,
    outreach_approved_at: null,
    email_sent: false,
    whatsapp_sent: false,
    replied: false,
    last_contacted_at: null,
    next_follow_up_at: null,
    notes: "No website detected; prioritize website development angle.",
    rating: 4.1,
    review_count: 6,
    missing_seo_metadata: false,
    contact_forms: [],
    do_not_contact: false,
    consent_status: "legitimate_interest",
    unsubscribed: false
  },
  {
    id: "lead_uk_1",
    company_name: "Borough Bistro",
    region: "UK",
    country: "United Kingdom",
    city: "London",
    category: "Restaurant",
    business_type: "Hospitality",
    website: "https://boroughbistro.example",
    google_maps_url: "https://maps.google.com/?q=Borough+Bistro",
    phone: "+44205550102",
    email: "bookings@boroughbistro.example",
    whatsapp_available: true,
    whatsapp_status: "delivered",
    owner_name: null,
    ceo_name: null,
    manager_name: "Amelia Carter",
    linkedin_url: null,
    source_platform: "google_places",
    outreach_status: "Replied",
    outreach_approved: false,
    outreach_approved_at: null,
    email_sent: true,
    whatsapp_sent: true,
    replied: true,
    last_contacted_at: new Date(now.getTime() - day * 2).toISOString(),
    next_follow_up_at: new Date(now.getTime() + day).toISOString(),
    notes: "Asked for a GBP audit.",
    rating: 3.7,
    review_count: 92,
    missing_seo_metadata: true,
    contact_forms: [],
    do_not_contact: false,
    consent_status: "legitimate_interest",
    unsubscribed: false
  },
  {
    id: "lead_uae_1",
    company_name: "Marina Aesthetic Clinic",
    region: "UAE",
    country: "United Arab Emirates",
    city: "Dubai",
    category: "Aesthetic clinic",
    business_type: "Healthcare",
    website: "https://marinaaesthetic.example",
    google_maps_url: "https://maps.google.com/?q=Marina+Aesthetic+Clinic",
    phone: "+97145550130",
    email: "info@marinaaesthetic.example",
    whatsapp_available: true,
    whatsapp_status: "available",
    owner_name: null,
    ceo_name: "Sara Al Nuaimi",
    manager_name: null,
    linkedin_url: null,
    source_platform: "google_places",
    outreach_status: "Follow-up",
    outreach_approved: false,
    outreach_approved_at: null,
    email_sent: true,
    whatsapp_sent: false,
    replied: false,
    last_contacted_at: new Date(now.getTime() - day * 3).toISOString(),
    next_follow_up_at: new Date(now.getTime() + day).toISOString(),
    notes: "High-value lead; local SEO opportunity.",
    rating: 4.7,
    review_count: 12,
    missing_seo_metadata: true,
    contact_forms: [],
    do_not_contact: false,
    consent_status: "legitimate_interest",
    unsubscribed: false
  },
  {
    id: "lead_qa_1",
    company_name: "Doha Fit Lab",
    region: "Qatar",
    country: "Qatar",
    city: "Doha",
    category: "Fitness center",
    business_type: "Wellness",
    website: null,
    google_maps_url: "https://maps.google.com/?q=Doha+Fit+Lab",
    phone: "+9745550194",
    email: null,
    whatsapp_available: false,
    whatsapp_status: "unknown",
    owner_name: null,
    ceo_name: null,
    manager_name: "Omar Hassan",
    linkedin_url: null,
    source_platform: "google_places",
    outreach_status: "Failed",
    outreach_approved: false,
    outreach_approved_at: null,
    email_sent: false,
    whatsapp_sent: false,
    replied: false,
    last_contacted_at: null,
    next_follow_up_at: null,
    notes: "Email discovery pending through website/search provider.",
    rating: 3.4,
    review_count: 3,
    missing_seo_metadata: false,
    contact_forms: [],
    do_not_contact: false,
    consent_status: "legitimate_interest",
    unsubscribed: false
  }
];

export const leads: Lead[] = seed.map((lead, index) => ({
  ...lead,
  lead_score: scoreLead(lead),
  created_at: new Date(now.getTime() - day * (index + 1)).toISOString(),
  updated_at: now.toISOString()
}));

export const notifications = [
  { id: "n1", type: "reply", title: "Reply received", message: "Borough Bistro asked for a GBP audit.", created_at: now.toISOString(), read: false },
  { id: "n2", type: "automation", title: "Automation completed", message: "Canada run finished with 8 actions logged.", created_at: new Date(now.getTime() - 3600000).toISOString(), read: false },
  { id: "n3", type: "lead", title: "High-value lead", message: "Marina Aesthetic Clinic scored 65.", created_at: new Date(now.getTime() - 7200000).toISOString(), read: true }
];

export const replies = [
  {
    id: "reply_1",
    lead_id: "lead_uk_1",
    from_email: "bookings@boroughbistro.example",
    subject: "Re: Quick Google Business Profile idea",
    body: "Thanks. Could you send over what you would improve first?",
    received_at: new Date(now.getTime() - 5 * 3600000).toISOString()
  }
];

export const aiDrafts = [
  {
    id: "draft_1",
    lead_id: "lead_uk_1",
    company_name: "Borough Bistro",
    draft: "Hi Amelia, thanks for getting back to me. I would start with your Google Business Profile categories, photo cadence, review response structure, and the missing page metadata that is limiting local discovery. I can send a short audit with priority fixes before any call.",
    status: "needs_review",
    created_at: new Date(now.getTime() - 4 * 3600000).toISOString()
  }
];
