import { aiDrafts, leads, notifications, replies } from "@/lib/mockData";
import { getRegion } from "@/lib/regions";
import { scoreLead } from "@/lib/scoring";
import type { AutomationResult, Lead } from "@/lib/types";

let leadStore = [...leads];
let notificationStore = [...notifications];
let replyStore = [...replies];
let aiDraftStore = [...aiDrafts];

export function listLeads(region?: string) {
  return region ? leadStore.filter((lead) => lead.region === region) : leadStore;
}

export function getLead(id: string) {
  return leadStore.find((lead) => lead.id === id);
}

export function listNotifications() {
  return notificationStore;
}

export function listReplies() {
  return replyStore;
}

export function listAiDrafts() {
  return aiDraftStore;
}

export function createDemoLeads(regionName: string) {
  const region = getRegion(regionName);
  const stamp = Date.now();
  const generated: Lead[] = [
    {
      id: `lead_${region.name.toLowerCase()}_${stamp}`,
      company_name: `${region.name} Growth Clinic`,
      region: region.name,
      country: region.country,
      city: region.name === "USA" ? "Austin" : region.name === "Canada" ? "Vancouver" : region.name === "UK" ? "Manchester" : region.name === "UAE" ? "Abu Dhabi" : "Doha",
      category: "Local service business",
      business_type: "SMB",
      website: null,
      google_maps_url: `https://maps.google.com/?q=${encodeURIComponent(`${region.name} Growth Clinic`)}`,
      phone: "+1555010101",
      email: `hello+${region.name.toLowerCase()}@example.com`,
      whatsapp_available: false,
      whatsapp_status: "unknown",
      owner_name: null,
      ceo_name: null,
      manager_name: "Operations Manager",
      linkedin_url: null,
      source_platform: process.env.GOOGLE_PLACES_API_KEY ? "google_places" : "demo_google_places",
      lead_score: 0,
      outreach_status: "New",
      outreach_approved: false,
      outreach_approved_at: null,
      email_sent: false,
      whatsapp_sent: false,
      replied: false,
      last_contacted_at: null,
      next_follow_up_at: null,
      notes: "Generated by safe demo automation. Configure official provider keys for live lead discovery.",
      rating: 3.5,
      review_count: 4,
      missing_seo_metadata: false,
      contact_forms: [],
      do_not_contact: false,
      consent_status: "legitimate_interest",
      unsubscribed: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    }
  ];
  generated[0].lead_score = scoreLead(generated[0]);
  leadStore = [...generated, ...leadStore];
  return generated;
}

export function markOutreach(leadId: string, channel: "email" | "whatsapp") {
  leadStore = leadStore.map((lead) => {
    if (lead.id !== leadId) return lead;
    return {
      ...lead,
      outreach_status: "Contacted",
      email_sent: channel === "email" ? true : lead.email_sent,
      whatsapp_sent: channel === "whatsapp" ? true : lead.whatsapp_sent,
      last_contacted_at: new Date().toISOString(),
      next_follow_up_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString()
    };
  });
}

export function completeAutomation(result: AutomationResult) {
  notificationStore = [
    {
      id: `notification_${Date.now()}`,
      type: result.status === "completed" ? "automation" : "failure",
      title: result.status === "completed" ? "Automation completed" : "Automation failed",
      message: `${result.region}: ${result.leadsFetched} leads, ${result.emailsSent} emails.`,
      created_at: new Date().toISOString(),
      read: false
    },
    ...notificationStore
  ];
}

export function analytics() {
  const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  return {
    daily: days.map((day, index) => ({
      day,
      leads: 8 + index * 3,
      emails: 5 + index * 2,
      whatsapp: 2 + index,
      replies: index % 2 === 0 ? 2 + index : 1 + index
    })),
    regions: ["Canada", "USA", "UK", "UAE", "Qatar"].map((region) => {
      const regionLeads = listLeads(region);
      return {
        region,
        leads: regionLeads.length,
        contacted: regionLeads.filter((lead) => lead.email_sent || lead.whatsapp_sent).length,
        replies: regionLeads.filter((lead) => lead.replied).length
      };
    }),
    funnel: [
      { name: "New Lead", value: leadStore.length },
      { name: "Contacted", value: leadStore.filter((lead) => lead.email_sent || lead.whatsapp_sent).length },
      { name: "Replied", value: leadStore.filter((lead) => lead.replied).length },
      { name: "Meeting Booked", value: leadStore.filter((lead) => lead.outreach_status === "Meeting Booked").length },
      { name: "Client", value: leadStore.filter((lead) => lead.outreach_status === "Closed").length }
    ],
    remaining: {
      emails: 450,
      whatsapp: 120,
      failed: leadStore.filter((lead) => lead.outreach_status === "Failed").length
    }
  };
}
